backend:
  name: github
  repo: gwahmp/wmao           # your GitHub repo path
  branch: main                # production branch

media_folder: "public/assets/images/blog"   # where images are stored in repo
public_folder: "/assets/images/blog"        # how site references images

publish_mode: editorial_workflow
slug:
  encoding: "unicode"
  clean_accents: true
  sanitize_replacement: "-"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "src/content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "md"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "description", label: "Description", widget: "text" }
      - { name: "h1", label: "H1", widget: "string" }
      - { name: "image", label: "Image (upload to /assets/images/blog)", widget: "image" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "author", label: "Author", widget: "string", default: "Selvakumaran Krishnan" }
      - { name: "category", label: "Category", widget: "string" }
      - { name: "tags", label: "Tags", widget: "list" }
      - { name: "summary", label: "Summary", widget: "text" }
      - name: "faq"
        label: "FAQ Section"
        widget: "list"
        fields:
          - { name: "q", label: "Question", widget: "string" }
          - { name: "a", label: "Answer", widget: "text" }
      - { name: "body", label: "Body", widget: "markdown" }
