backend:
  name: git-gateway
  branch: main
  site_domain: www.wikimint.com

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "src/content/posts"
    create: true
    slug: "{{slug}}"  # <-- filename only, no date
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "H1", name: "h1", widget: "string" }
      - { label: "Image (upload 1200px version)", name: "image", widget: "image" }
      - { label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD" }
      - { label: "Author", name: "author", widget: "string", default: "selvakumaran-krishnan" }
      - { label: "Category", name: "category", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Summary", name: "summary", widget: "text" }
      - label: "FAQ"
        name: "faq"
        widget: "list"
        fields:
          - { label: "Question", name: "q", widget: "string" }
          - { label: "Answer", name: "a", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
